### PR TITLE
✨  NEW: Markdown math

### PR DESCRIPTION
**Pull request by rowanc1**
- [x] Add equation numbers
- [x] Test targets of equation numbers (likely adding types)

See #4

### CODE REVIEW

**Comment by rowanc1** [comment]
Basic equation numbering.

Note that the example doesn't yet render math.

image

**Comment by choldgraf** [comment]
This sounds cool! Is there some way that I can test this out? Maybe we can set up a little sphinx build that loads the JS/HTML libraries for this?

**Comment by rowanc1** [comment]
Put this together:

https://markdown-it-myst.glitch.me/

Won't have the math stuff in it, but the latest deployed version!

**Comment by choldgraf** [comment]
awesome! (though in this case I specifically wanted to try out the new behavior of this PR myself.

for those of us that don't speak JS very well, do you think you could add a simple set of instructions for how to compile this library locally, and a little lightweight HTML file that lets us demo locally?

though I don't think this kinda stuff should block merging since this codebase is so young, so I'm happy if you wanna 🚢 it

**Comment by rowanc1** [comment]
Sounds good. I will detail that in another PR!

Ran out of time tonight .. will finish Sunday!

**Comment by rowanc1** [comment]
I will add a bit more to the readme around starting up the dev environment, it should be straight forward after you get [yarn installed](https://classic.yarnpkg.com/en/docs/install), on a mac - something like this:

```
brew install yarn
cd markdown-it-myst
yarn install
yarn start
```

Install the packages and start the server, there is also a `yarn test` in there that goes through all of the fixtures at the moment.

**Pull request merged**
