### PR TITLE
📖  DOCS: Add developer install instructions

### PR DESCRIPTION
**Pull request by rowanc1**
Add install instructions, please modify or ask questions to get up and running and we can clarify the readme!

### CODE REVIEW

**Comment by choldgraf** [comment]
woo - these worked for me!

**Comment by choldgraf** [comment]
One thought - we could separate the three `dev` commands into three sections, and add more explanatory text about what to expect (rather than using in-line comments for them). E.g., I think that running `yarn start` also runs `yarn build` first? Or maybe not? Either way, just giving people a bit more idea of what to expect could help for a non-seasoned JS-er

**Comment by rowanc1** [comment]
Cool, added a bit more explanation for each!

The `start` does an in-memory build, and isn't quite the same as the build command, I added this note to the docs.

**Comment by choldgraf** [comment]
LGTM - thanks! 🎉

**Comment by choldgraf** [comment]
oops - forgot to squash-merge...oh well. I just activate it as the default for our PRs

**Pull request merged**
